name: David Leger
markdown: redcarpet
redcarpet:
  extensions: ["autolink", "tables"]
exclude: ["node_modules",
  "gulpfile.js",
  "package.json",
  "preview.jpg",
  "README.md"]

baseurl: '/whitespace'
highlighter: pygments
